# Generated by Django 4.2 on 2023-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedatabase',
            name='quality',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
